wnba_dbt:
  target: prod
  outputs:
    prod:
      type: postgres
      host: "{{ env_var('SUPABASE_HOST', 'db.ztnuuxnqbfiyypedtuaw.supabase.co') }}"
      user: "{{ env_var('SUPABASE_USER', 'postgres') }}"
      password: "{{ env_var('SUPABASE_PASSWORD', 'JacksonJ236565!!') }}"
      port: 5432
      dbname: "{{ env_var('SUPABASE_DBNAME', 'postgres') }}"
      schema: "{{ env_var('SUPABASE_SCHEMA', 'wnba') }}"
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      retries: 3
      sslmode: require
